kind: pipeline
name: rsschool-api
steps: 
  - 
    commands:
      - "npm install"
      - "npm run lint"
      - "npm run test"
      - "npm run build"
    image: "node:10"
    name: build
    volumes: 
      - name: cache
        path: /root/.npm
  - 
    name: docker
    image: plugins/docker
    settings:
      repo: rsschool/api
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
    when: 
      branch:
        - master
      event: 
        - push
  - 
    name: deploy
    image: appleboy/drone-ssh
    settings:
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      command_timeout: 2m
      host: "172.31.2.208"
      port: 22
      script: 
        - "sleep 10"
        - "docker pull rsschool/api:latest"
        - "docker-compose stop api"
        - "docker-compose rm -f api"
        - "docker-compose up -d api"
        - "docker system prune -f"
    when: 
      branch: 
        - master
      event: 
        - push
volumes:
- name: cache
  host:
    path: /temp/cache