pipeline:
  build:
    image: node:8.11
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: rsschool/api
    tags: latest
  deploy:
    image: appleboy/drone-ssh
    host: 172.31.2.208
    secrets: [ ssh_key, ssh_username ]
    port: 22
    command_timeout: 60
    script:
      - docker pull rsschool/api
      - docker-compose stop api
      - docker-compose rm -f api
      - docker-compose up -d api
