service:
  name: github-task-checker

plugins:
  - serverless-plugin-typescript

package:
  individually: true

provider:
  name: aws
  stage: prod
  runtime: nodejs10.x
  profile: rsschool
  region: eu-central-1
  memorySize: 128
  timeout: 60
  apiKeys:
    - github-task-checker
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt: [JsTasksQueue, Arn]
    # - Effect: Allow
    #   Action:
    #     - sqs:SendMessage
    #   Resource:
    #     Fn::GetAtt: [HtmlTasksQueue, Arn]
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt: [ExternalTasksQueue, Arn]

resources:
  Resources:
    JsTasksQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: tasks-js
        VisibilityTimeout: 61
    ExternalTasksQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: tasks-external
        VisibilityTimeout: 61
    # HtmlTasksQueue:
    #   Type: AWS::SQS::Queue
    #   Properties:
    #     QueueName: tasks-html
    #     VisibilityTimeout: 61

functions:
  # CheckHtmlTask:
  #   handler: handlers/htmlTask.handler
  #   events:
  #     - sqs:
  #         batchSize: 1
  #         arn:
  #           Fn::GetAtt: [HtmlTasksQueue, Arn]

  CheckExternalTask:
    handler: handlers/externalTask.handler
    memorySize: 256
    timeout: 30
    package:
      exclude:
        - 'node_modules/chrome-aws-lambda/**'
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt: [ExternalTasksQueue, Arn]
    environment:
      RS_APP_AUTHORIZATION: '{{resolve:ssm:rs-app-authorization:1}}'

  CheckJsTask:
    handler: handlers/jsTask.handler
    memorySize: 256
    timeout: 30
    package:
      exclude:
        - 'node_modules/chrome-aws-lambda/**'
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt: [JsTasksQueue, Arn]
    environment:
      RS_APP_AUTHORIZATION: '{{resolve:ssm:rs-app-authorization:1}}'

  SubmitTask:
    handler: handlers/submitTask.handler
    package:
      exclude:
        - node_modules/**
        - '!node_modules/lodash/**'
    environment:
      JSTASK_SQS_URL:
        Ref: JsTasksQueue
      # HTMLTASK_SQS_URL:
      #   Ref: HtmlTasksQueue
      EXTERNAL_TASK_SQS_URL:
        Ref: ExternalTasksQueue
    events:
      - http:
          method: post
          path: task
          private: true
